# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "forwarded_port", guest: 5000, host: 9001
  config.vm.network "forwarded_port", guest: 80, host: 9081
  config.vm.provision "shell", inline: <<-SHELL
    # Update the package lists and install Python, Flask, Gunicorn, and Nginx
    sudo apt-get update -y
    sudo apt-get install python3-pip python3-dev nginx -y

    sudo pip3 install flask flask-cors gunicorn

    # Start Nginx service and enable it to start at boot
    # sudo systemctl start nginx
    # sudo systemctl enable nginx

    sudo wget --no-cache -O flaskapi.py https://raw.githubusercontent.com/jamangi/shauntal-data-training/main/Lab-4-nginx-proxy/flaskapi.py
    sudo wget --no-cache -O wsgi.py https://raw.githubusercontent.com/jamangi/shauntal-data-training/main/Lab-4-nginx-proxy/wsgi.py
    sudo wget --no-cache -O /etc/systemd/system/flaskapi.service https://raw.githubusercontent.com/jamangi/shauntal-data-training/main/Lab-4-nginx-proxy/flaskapi.service

    sudo systemctl daemon-reload
    sudo systemctl start flaskapi
    sudo systemctl enable flaskapi
    sudo systemctl status flaskapi

    sudo wget --no-cache -O /etc/nginx/sites-available/flaskapi.conf https://raw.githubusercontent.com/jamangi/shauntal-data-training/main/Lab-4-nginx-proxy/flaskapi.conf
    sudo ln -s /etc/nginx/sites-available/flaskapi.conf /etc/nginx/sites-enabled/
  SHELL
end
